spring:
  application:
    name: booking
  datasource:
    url: jdbc:postgresql://localhost:5432/your_db
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
jwt:
  secret: 4BjKlm8pP2qN6tR7s9XyVZ3aH0FgW5yQ
  expiration: 3600

logging:
  level:
    root: INFO
    com.example.booking: DEBUG
  file:
    name: logs/app.log
debug: false